[package]
name = "datjit-output"
version.workspace = true
edition.workspace = true

[dependencies]
datjit-core.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
csv.workspace = true
indexmap.workspace = true
chrono.workspace = true
uuid.workspace = true
